### ISSUE TITLE
Expose Since property received from pocket server for Retrieve response.

### ISSUE THREAD

**Issue by SriramSakthivel** [ceee/PocketSharp#30]
From pocket documentation in [Best practices section](http://getpocket.com/developer/docs/v3/retrieve).

>>After retrieving the list, you should store the current time (**which is provided along with the list response**) and pass that in the next request for the list

I'm trying to save the `Since` property returned by server, so that next time I can request from that time; But it seems it is not exposed in the PocketClient API (Unless I'm missing something).

I can see the [Since property in source code]( https://github.com/ceee/PocketSharp/blob/master/PocketSharp/Models/Response/Retrieve.cs#L29). If this is what the documentation is talking about, please expose it in the API. 

It will be very helpful, otherwise we need to rely on our local machine time which is likely to invite time synchronization problems.

If I'm misunderstanding something please correct me.

Thanks in advance.

**Comment by ceee** [comment]
Please take a look at the Wiki or _public_ methods which are available for the user. The `since` parameter is passed as a param into the `Get` method. https://github.com/ceee/PocketSharp/wiki/Get

You do get your `DateTime` instance with Kind.UTC, and that's how PocketSharp handles it. In case you modify the DateTimeKind it gets corrected to UTC again before sent to the Pocket API.

**Comment by SriramSakthivel** [comment]
@ceee I understand that I've to use `Get` method which supports `since` parameter. In fact I've already implemented it and working fine. My suggestion/question is rather different.

I'm asking where to get the `since` parameter from? Pocket api documentation says that I need to store the `DateTime` which was returned with the list response fro pocket server. But I have no way to access the returned `DateTime` property. Please refer the quote which I have linked in my original question.

Do you recommend me to store my device time itself (of course in UTC)? or Any chance of exposing the DateTime returned from pocket server in public API?

Am I being clear? Or you need me to explain any better?

Thanks.

**Comment by ceee** [comment]
Alright, sorry, didn't understand it.

I guess I did not add this as I don't see any benefit in doing so. It only returns the time before (or after) processing your request, and that can be easily queried on the client too (with the downside of a few ms/secs difference). If the client has a wrong time set, the passed (and returned) since parameter would be incorrect too.

It's such a rare case that this time calculation could fail that I don't plan to change this behaviour as I would have to change the method signature too (and for all other affected methods).
