### ISSUE TITLE
Empty callback Url?

### ISSUE THREAD

**Issue by derekantrican** [ceee/PocketSharp#38]
Currently, this is how I'm authenticating with PocketSharp:

    public static void AuthPocket()
    {
        PocketClient = new PocketClient(ConsumerKey);
        PocketClient.CallbackUri = "https://getpocket.com/a/queue/"; //Todo: prevent this from opening
        string requestCode = PocketClient.GetRequestCode().Result;
        Uri authenticationUri = PocketClient.GenerateAuthenticationUri();
        Process.Start(authenticationUri.ToString());
    
        PocketUser user = null;
        while (true)
        {
            try
            {
                user = PocketClient.GetUser(requestCode).Result;
                break;
            }
            catch { }
            System.Threading.Thread.Sleep(500);
        }
    
        PocketClient = new PocketClient(ConsumerKey, user.Code);
    }

My main problem is that every time this code runs, it opens the callback url in the user's browser. Is there a way I can avoid that? I know I can just save the `user.Code` in a file somewhere but I want my program to not have to write to any "settings" files

**Comment by ceee** [comment]
I do not know where you have this code from, but this is dead wrong.
You are introducing deadlocking issues by calling `.Result` on the public async methods of PocketSharp.
Same goes for your infinite loop where you are calling `GetUser`.

The reason why your code is launching the browser is because this is the default when calling `Process.Start` with an URL as the parameter.

There is no way to authenticate a user without presenting a web form, as the user has to authenticate your application within the Pocket context (on getpocket.com).

I have documented the authentication process here: https://github.com/ceee/PocketSharp/wiki/Account-Authentication

**Comment by derekantrican** [comment]
I understand that what I'm doing is probably not great, but if I do this:

    public static async Task AuthPocket()
    {
        PocketClient = new PocketClient(ConsumerKey);
        PocketClient.CallbackUri = "https://getpocket.com/a/queue/"; //Todo: prevent this from opening
        string requestCode = await PocketClient.GetRequestCode();
        Uri authenticationUri = PocketClient.GenerateAuthenticationUri(requestCode);
        Process.Start(authenticationUri.ToString());
    
        PocketUser user = await PocketClient.GetUser(requestCode);
    
        PocketClient = new PocketClient(ConsumerKey, user.Code);
    }

I get `PocketException: Pocket error: User rejected code. (158)`. Which is why I had added the `while` loop with a delay. Am I following the wiki page wrong?

**Comment by ceee** [comment]
The `authenticationUri` is the URI the browser (or WebView) has navigate to.
When the user grants permission for this application, they will get an **access code** in response.
You will need to pass the access code to the `PocketClient.GetUser()` and not the request code.

**Comment by derekantrican** [comment]
I'm confused then. https://github.com/ceee/PocketSharp/wiki/Account-Authentication says

>Note that `GetUser` can only be called with an existing *request code*.

Is that wrong?
